### ISSUE TITLE
/data/dbus-opendtu/uninstall.sh did NOT prevents it from being restarted

### ISSUE THREAD

**Issue by gerd-git** [henne49/dbus-opendtu#103]
**Describe the Problem**
/data/dbus-opendtu/uninstall.sh did NOT prevents it from being restarted

**Device you are using**
Venus OS v3.00
raspberrypi2
opendtu

**Expected behavior**
"/data/dbus-opendtu/uninstall.sh stops the service and prevents it from being restarted (e.g. after a reboot)."

```
root@raspberrypi2:~# /data/dbus-opendtu/uninstall.sh
root@raspberrypi2:~# reboot
Broadcast message from root@raspberrypi2 (pts/0) (Wed Jul 12 10:46:29 2023):
The system is going down for reboot NOW!
root@raspberrypi2:~#
login as: root
root@venus.local's password:
Last login: Wed Jul 12 10:47:12 2023
root@raspberrypi2:~# svstat /service/dbus-opendtu
/service/dbus-opendtu: up (pid 2024) 178 seconds
root@raspberrypi2:~#
```

**Comment by henne49** [comment]
I can confirm this. 

The problem is that we write the install.sh script into /data/rc.local
for firmware upgrades. we need to delet the entry from rc.local to fix this.

**Comment by henne49** [comment]
PR Request is submitted to fix it
