### ISSUE TITLE
If using L2 in config.ini, device is not shown in VRM

### ISSUE THREAD

**Issue by Gelegenheitsbastler** [henne49/dbus-opendtu#106]
**Describe the Problem**
I flashed a tasmota to an Sonoff POW Elite like shown on here: https://www.youtube.com/watch?v=fsexD8-rJl4
I did the changes into config.ini and everything works fine. Device is shown into the remote console and into VRM.

Then I configured a second Sonoff POW Elite the same way, but not on L1 like the first one. The second device is at L2. The device is shown at the remote console but not at VRM. 
If I only change L2 to L1 at the config.ini the device is shown at the VRM. By returning to L2 the device is no longer at VRM.
Seems to be a bug at using L2.

**Device you are using**
1. Which Venus OS are you using? 3.0 @ raspberry Pi
3. Which Victron Device? 
4. Which DTU? --> see description
5. Which Template Device? --> see description

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 0x7878** [comment]
VRM Portal works a little bit differently. If the data is shown on your local console then I'm afraid there's nothing we can do about it. You have to know that VRM does only work with their own products. Everything else (also a different config) might not work. 

For instance: my Multiplus 2 is running on L2. It is working but the calculation for AC Out is completely wrong due Victron supposed it runs on L1. (There is no setting anyway)
