### ISSUE TITLE
Why extra package?

### ISSUE THREAD

**Issue by New-three** [henne49/dbus-opendtu#11]
Why I must install this? I have a Victron 5000 GX.

opkg install python3-pip 
pip3 install suntime
pip3 install pytz

**Comment by henne49** [comment]
you don't ignore it for now

**Comment by New-three** [comment]
I don't understand the answer.

I have not installed these packages. anyway everything works. should this installation ensure that all additional packages are really installed? Or are there extra functions after the installation?

**Comment by henne49** [comment]
Sorry missed a comma in my response. these packages were for a new feature idea. So for now this is not required at all.
