### ISSUE TITLE
AcPosition=0 is not showing in RemoteConsole/Dashboard

### ISSUE THREAD

**Issue by svenshub** [henne49/dbus-opendtu#110]
**Follow the Troubleshooting Section**
Change the Logging Parameter under DEFAULT in /data/dbus-opendtu/config.ini to Logging = DEBUG, please revert, once debugging and troubleshooting is complete. Rerun the script and share the current.log and config.ini file.
[Troubleshooting Section](https://github.com/henne49/dbus-opendtu#troubleshooting )

**Describe the Problem**
I have 2 Hoymiles PV Inverter physically connected tho the OpenDTU.
When AcPosition=0 (ac_input) is entered in the config.ini, then they don‘t show on the Remote Console / Dashboard.
With AcPosition=1 it works!
But, if i use the the AcPosition=1 (ac_output) in the config.ini, then is the AC_Loads calculation incorrect.
What can i do?

**Device you are using**
1. Which Venus OS are you using? -> FW: v3.10-32 @raspberryPI 3B
2. Which Victron Device? -> MP2 3000 / 48
3. Which DTU? -> OpenDTU / FW: v23.8.22
4. Which Template Device? -> Two Hoymiles HM600, (more to come)

**Expected behavior**
AC_IN coppled PV Inverter with correct show on the Remote Console / Dashboard and correct AC_Loads calculation.

**Screenshots**
AC_Position = 0
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/a72683b8-ece7-4983-a850-6b2e0c57a19b)

AC_Position = 1
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/dde59124-ae6b-4fc5-875d-27bc1c6900ed)

**Additional context**
[config.ini.txt](https://github.com/henne49/dbus-opendtu/files/12496837/config.ini.txt)
[current.log](https://github.com/henne49/dbus-opendtu/files/12496838/current.log)

**Comment by henne49** [comment]
Do you have another PV or only hoymiles? Can you try to downgrade the multiplus firmware?

**Comment by henne49** [comment]
Can you see the Hoymiles in the DeviceList, even with AcPosition=0?
<img width="477" alt="image" src="https://github.com/henne49/dbus-opendtu/assets/4662326/1e2fda8b-b116-447b-9728-930c2856577a">

**Comment by svenshub** [comment]
hello henn49,
thank you for your feedback.

In this 1st install phase, i have only two Hoymiles interverter installed yet. More to come.

The grid meter is SDM630 type and is emulated with the bridge from:
https://github.com/stormmurdoc/victron_sdm630_bridge
The Source data comes from:
https://github.com/volkszaehler/mbmd
and this setup running normaly.

Grid meter:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/0e6b6f93-ead2-495f-9b71-c030ba93e84d)

1st Hoymiles interver:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/047f11b2-8f4d-4681-8028-0fbed8df95f8)

2nd: Hoymiles inverter:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/c10291e0-7705-4e07-b1aa-7109878247c6)

Device List in AcPosition=0:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/84fdd25c-32f3-4c39-ad3a-1f3b1a081a53)

The raw data are in venusOS included and in victronVRM reported:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/468be751-930d-46ae-af36-ead2c68ae6fc)


**The problem is, i can´t see the PV inverter with the config.ini AcPosition=0 in the remote console!**
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/f904a26a-a148-4ba1-b21e-1f3b2867b1d6)

I tested multiple settings with the Gui Mods settings:
(Flow overwiev=simple, =DC Coupled, =AC Coupled, Victron Stock as well)
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/ba0e4cd0-a643-45d5-a522-8ea455a1c34c)

and together in combination with AC input/output loads and Show Loads On Input: 
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/13b498a8-cd0c-4e87-a53b-ea9723887fc1)

But in AcPosition=0 is **NO** PV Inverter displayed in the remote Console:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/de2efcd9-0c12-4dc1-b669-340790256ae5)

######

If i switch the two invter in the config.ini to AcPosition=1, the inverter are now displyed. Looks like good:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/31a40dcd-ddb6-49d9-aae2-8d3eb91268d3)

But in the 3 phase details view, you can see, the AC Loads calulation is wrong.
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/409e70ce-4b83-4ab1-ad14-61d441d43b71)

The negatives AC Input phases (L1 and L3) are not subtracted in the AC Loads!
The PV Inverter Power (L1 and L3) are 1 to 1 in the AC Loads displayed.

Where is the bug?
Thank you for your help.

regards
sven

**Comment by svenshub** [comment]
additional comment:

I tested with the following venus OS firmware on a Raspberry Pi 3B:
-v3.01
-v3.10-32
-v3.10-34 (currently installed)

The same results.

regards
sven

**Comment by henne49** [comment]
Sorry, it seems that it is more a display issue, than a bug, it works for me also with latest release candidate, I do not even know where to change the GUI display mode.

**Comment by henne49** [comment]
can you also check the VRM Portal, what is displayed there?

**Comment by Cassiopea1** [comment]
Hi,

Same here. I've just installed the HM-1500, but it does not show up in the Overview page or VRM as PV inverter.
Venus OS large v3.01

![Overview](https://github.com/henne49/dbus-opendtu/assets/84228832/ebdf770e-5c89-411f-bec1-3c755b8dd11c)
![Devices](https://github.com/henne49/dbus-opendtu/assets/84228832/f9e4280e-5e32-44a5-8a6d-b36a89086576)
![HM-1500](https://github.com/henne49/dbus-opendtu/assets/84228832/5d71e8e8-1948-4565-89f7-aa315de83211)

My config.ini :

`[DEFAULT]
SignOfLifeLog= 1

NumberOfTemplates=0

DTU=ahoy

useYieldDay=0

ESP8266PollingIntervall=10000

Logging=ERROR

MaxAgeTsLastSuccess=600

DryRun=0

Host=192.168.1.147

HTTPTimeout=2.5

Username =
Password =

[INVERTER0]
Phase=L1
DeviceInstance=34
AcPosition=0
Servicename=com.victronenergy.pvinverter
`

**Comment by svenshub** [comment]
with config.ini setup AcPosition=1 looks like as follow:

remote console overview:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/6ffce5fb-c723-42f3-b83a-6a2f6453c810)
remote console device List:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/2d643a01-918a-4398-a2bf-0793618461e6)

VRM Portal:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/f908a9d7-f6fb-4311-80b5-940dfc406771)
update is life:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/8e14202d-510f-4aa2-887c-bb4700f7b315)

but both views with **incorrect AC Loads** (see L1 and L3 Loads).

------

with config.ini setup AcPosition=0 looks like as follow:
remote console overview:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/ba10b18a-95a4-4a6d-8f05-c76e17b1e781)
remote console device List:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/b2365496-1138-43c2-b369-e24bb703dc20)

VRM Portal:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/0f0f853d-7c6f-4b30-b063-dae5a2870afc)
update is also life:
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/ae6386ca-10be-4279-8f8c-a7766924c530)

you see, the data inputs are correct and reported to the VRM Portal.
But i have no PV Inverter in the remote console and also the **incorrect AC Loads** (see L1 and L3 Load = 0 Watts).

I use the GuiMods v8.02
![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/d24c3bda-9d9a-4f88-a2d6-522706801e8d)
mey be there is the problem?!?

But in the Victron stock overview, also no PV Inverter displayed and the AC Loads are incorrect.

Witch module is calculating the AC Loads?

**Comment by hd-schardt** [comment]
Hello,
I can confirm the same behaviour here with me.
VenusOS 3.01 large
Greetings Heinz-Dieter

**Comment by 0x7878** [comment]
I think Victron changed something in their major version (3.0) and above. I'm running 3 inverters in Total on AC position 0. 

I'm sorry for your situation but I don't think that there is anything we can do about it. 

![Screenshot_20230907-185318](https://github.com/henne49/dbus-opendtu/assets/17197791/dbb8c639-15f0-40f3-8c6f-564524b752ae)
![Screenshot_20230907-185447](https://github.com/henne49/dbus-opendtu/assets/17197791/c09402df-9a83-4cea-bd2a-f25cf8ae531a)

**Comment by hd-schardt** [comment]
I also think it is due the changeover to Version 3.x and possibly also to changes in the VRM.
Thanks for your help!

**Comment by hd-schardt** [comment]
I also think it is due the changeover to Version 3.x and possibly also to changes in the VRM.
Thanks for your help!

**Comment by henne49** [comment]
Let us check, if we need to set the inverter value negativ for newer Venus Versions.

**Comment by henne49** [comment]
that does not work as well. Then Critical Loads is 0. 

So for now, nothing we can do. 
<img width="772" alt="image" src="https://github.com/henne49/dbus-opendtu/assets/4662326/678fc18b-326b-4939-8e92-0d8fb1d0dbda">

**Comment by svenshub** [comment]
Thank you all for your inputs!

I downgraded the firmware to last v2.x (v2.94) version, and everything is fine!
The two inverter ar now running in AcPosition=0 (where they are physicly located as well) and the AC Load calculation is correct now!

Thanks a lot.

regards
sven

![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/ed01dedf-8927-456b-93e0-e3017ee30ba3)

![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/85e03d24-0f72-4e00-bee8-a8e0c405748b)

![grafik](https://github.com/henne49/dbus-opendtu/assets/127954083/d0e79f37-2918-4e3f-8db3-ea91252d61a1)

**Comment by DerJungeHerr** [comment]
@henne49 @svenshub is there any news from Victron about this behavior?

**Comment by 0x7878** [comment]
@DerJungeHerr At the moment it's still the same situation. No one has tried a newer version because of various problems. If there is a new version you could try and tell us if something has changed. The documentation from Victron does not change and we have done everything as described.

**Comment by DerJungeHerr** [comment]
> @DerJungeHerr At the moment it's still the same situation. No one has tried a newer version because of various problems. If there is a new version you could try and tell us if something has changed. The documentation from Victron does not change and we have done everything as described.

I installed the latest beta  3.1xxxx something .... still not working. I will downgrade my system to the last working version 2.94 .. I hope Victron is working on the issue ...

**Comment by 0x7878** [comment]
> > @DerJungeHerr At the moment it's still the same situation. No one has tried a newer version because of various problems. If there is a new version you could try and tell us if something has changed. The documentation from Victron does not change and we have done everything as described.
> 
> I installed the latest beta  3.1xxxx something .... still not working. I will downgrade my system to the last working version 2.94 .. I hope Victron is working on the issue ... 

Thanks for your time and effort. I hope so, too.

**Comment by Cassiopea1** [comment]
For me the problem corrected by itself after I actually installed the multiplus. It just appeared...

<img width="362" alt="image" src="https://github.com/henne49/dbus-opendtu/assets/84228832/4b4615ab-a4a1-425f-bc55-9d05b9fca3f6">

**Comment by DerJungeHerr** [comment]
> For me the problem corrected by itself after I actually installed the multiplus. It just appeared...
> 
> <img alt="image" width="362" src="https://user-images.githubusercontent.com/84228832/273175557-4b4615ab-a4a1-425f-bc55-9d05b9fca3f6.png">

Version of VenusOS ? Can you give more details about your System?

@henne49 @0x7878 @svenshub I will start an issue soon I guess I will inform you here, maybe we can push it a little bit in the Victron Venus repo ;)

**Comment by Cassiopea1** [comment]
> > For me the problem corrected by itself after I actually installed the multiplus. It just appeared...
> > <img alt="image" width="362" src="https://user-images.githubusercontent.com/84228832/273175557-4b4615ab-a4a1-425f-bc55-9d05b9fca3f6.png">
> 
> Version of VenusOS ? Can you give more details about your System?
> 
> @henne49 @0x7878 @svenshub I will start an issue soon I guess I will inform you here, maybe we can push it a little bit in the Victron Venus repo ;)

Venus OS: v3.10 on RPi4
Ahoy DTU: v0.7.36

When I integrated the HM-1500 into the Venus OS, the multiplus was not connected to the Venus OS (was not delievered at that time) and the PV Inverter was not visible on the display. Later, when I connected the multiplus, the PV Inverter appeared on the display.

**Comment by addo88** [comment]
Same Problem with my HM-600 and HM-800 via ahoyDTU,  subscribed and hopefully 

will temporary downgrade to ver. 2.94 :(

 @henne49 thanks a lot for your amazing work !!!
