### ISSUE TITLE
Explanation "number of template inverter to query"

### ISSUE THREAD

**Issue by TestOr90** [henne49/dbus-opendtu#111]
Hi everyone!

I have a very simple question, can someone explain what the "number of Template inverter to query" means?

Its in the config.ini file, and im sorry i dont understand it.

Also i only wanted to install the DTU, but in the Cerbo device list I also have the entries:
"Tasmota"
"Shelly 1PM"
"ShellyPlus 1PM"

Thank you!

**Comment by henne49** [comment]
It means how man template inverter you want to query. If you have only 1 let it 1. 3 Shellies should be 3, if you have 4 you need to add a forth and so ob to the config.ini

**Comment by henne49** [comment]
no response closing
