### ISSUE TITLE
How to delete Tasmota Tap

### ISSUE THREAD

**Issue by Mashup39** [henne49/dbus-opendtu#115]
Hello, first of all, thank you for this nice piece of Software.

I currently have the problen, that in  the venus OS, I see a tap called Tasmota. It is in the config.ini.

I dont need that Tap.

How can i delete this?

**Comment by henne49** [comment]
Change NumberOfTemplates = 0

**Comment by Mashup39** [comment]
Thank you very much.  I thought, I have to put in the number of inverters😅

**Comment by Mashup39** [comment]
Problem solved

**Comment by Mashup39** [comment]
Problem solved
