### ISSUE TITLE
Show "Total Yield"

### ISSUE THREAD

**Issue by andreas-bulling** [henne49/dbus-opendtu#121]
It'd be nice if "Total Yield" would be shown in Venus OS like it is for MPPTs.

**Comment by henne49** [comment]
where should this be shown? as we do show total Yield

<img width="510" alt="image" src="https://github.com/henne49/dbus-opendtu/assets/4662326/5a967d91-0c4d-46f8-92de-7f8488ef495c">

**Comment by andreas-bulling** [comment]
True - sorry, I missed that.

**Comment by andreas-bulling** [comment]
Ah, but there is something else: I am using a used inverter that accumulated kWh already. I can fix the display in the OpenDTU webinterface through a negative offset but in the remote console the total is shown (i.e. the offset is not taken into account)

**Comment by henne49** [comment]
Where can you configure a negative offset? If that is not working please report the issue at opendtu, as they need to provide the right data via api

**Comment by andreas-bulling** [comment]
Inverter Settings -> String

**Comment by henne49** [comment]
yep and that works as it should.

**Comment by andreas-bulling** [comment]
No, it doesn't. See

https://github.com/tbnobody/OpenDTU/issues/1512#issuecomment-1817970649

**Comment by henne49** [comment]
Use useYieldDay=1 in config.ini
________________________________
Von: andreas-bulling ***@***.***>
Gesendet: Sunday, November 19, 2023 9:40:49 PM
An: henne49/dbus-opendtu ***@***.***>
Cc: henne49 ***@***.***>; State change ***@***.***>
Betreff: Re: [henne49/dbus-opendtu] Show "Total Yield" (Issue #121)


No, it doesn't. See

tbnobody/OpenDTU#1512 (comment)<https://github.com/tbnobody/OpenDTU/issues/1512#issuecomment-1817970649>
