### ISSUE TITLE
keine Anzeige im VRM-Dashboard, in Remote-Konsole nur Anzeige von "VA" (keine Watt-Angabe)

### ISSUE THREAD

**Issue by ahhkoch** [henne49/dbus-opendtu#129]
**Follow the Troubleshooting Section**
Change the Logging Parameter under DEFAULT in /data/dbus-opendtu/config.ini to Logging = DEBUG, please revert, once debugging and troubleshooting is complete. Rerun the script and share the current.log and config.ini file.
[Troubleshooting Section](https://github.com/henne49/dbus-opendtu#troubleshooting )

**Describe the Problem**
In CerboGX-Remote-Console only value in "VA" is shown, not "Watt"

**Device you are using**
Hoymiles-600 with OpenDTU on ESP32, CerboGX

1. Which Venus OS are you using? => latest
3. Which Victron Device? => MP2, MPPT, CerboGX, SmartShunt
4. Which DTU => OPENDTU
5. Which Template Device? => None? Not required for Opendtu?

**Expected behavior**
See the OpenDTU in VRM as PV-Inverter with "Watts"
See the OpenDTU "Watt"-Value in Remote-Console

![2023-12-17 13_41_53-Clipboard](https://github.com/henne49/dbus-opendtu/assets/95191476/4edc6288-2fa8-48d4-b474-0b6f6d25fa69)

**Screenshots**

**Additional context**
My OpenDTU has the name "Stromer".

**Comment by henne49** [comment]
Kannst du bitte die genaue Version des Venus OS angeben und die Konfig Datei anhängen, bitte nicht einfach rein pasten. 

Ist der der Schuppen auch eine OpenDTU?

**Comment by ahhkoch** [comment]
Schuppen ist ein Victron-MPPT. 
Einen Fronius WR gibt es auch noch.

VenusOS ist Version 3.13

[config.ini.txt](https://github.com/henne49/dbus-opendtu/files/13701847/config.ini.txt)

**Comment by henne49** [comment]
bitte mal die Line Servicename=com.victronenergy.inverter löschen, dann setzen wir den richtigen Default Service für PV Inverter. Ich habe auch auf die 3.13 geupdated uns schaue morgen mal, wenn die Sonne scheint, ob ich dann da VA oder W habe. Ich glaube aber es liegt am Servicename, den du falsch gesetzt hast

**Comment by ahhkoch** [comment]
Hi,
jetzt sehe ich in der Remotekonsole  auch korrekt die W-Angabe. Danke dafür! :) Nur im Dashboard erscheint da nix vom dem Opendtu-PV-Inverter. Das wäre natürlich perfekt...

Grüße
![2023-12-19 12_20_42-RaptorPower - VRM Portal](https://github.com/henne49/dbus-opendtu/assets/95191476/fcd62bbf-0abf-49ec-8968-aa5a8c9fbe06)

**Comment by henne49** [comment]
er sollte im Fronius versteckt sein ACPosition steht auf 0 bei dir. 

 Position shown in Remote Console (0=AC input 1; 1=AC output; 2=AC input 2 please do not use)

**Comment by henne49** [comment]
Ins Dashboard geht nicht separat, du nur über den AC Out was machen, wenn da noch nichts ist. Aber dann ist es eben auch falsch, wenn es an AC In hängt. 

Danke für das Lob, das muss ich aber an die echten Kollegen wie @0x7878 und @dsteinkopf weitergeben.
