### ISSUE TITLE
Service scheint nicht zu starten

### ISSUE THREAD

**Issue by Jch24** [henne49/dbus-opendtu#130]
[current.log](https://github.com/henne49/dbus-opendtu/files/13719483/current.log)
[config.zip](https://github.com/henne49/dbus-opendtu/files/13719486/config.zip)
Hallo,

ich versuche seit 2 Tagen das Projekt hier zum laufen zu bekommen. Ich habe die config.ini angepasst nach bestem Wissen und Gewissen. Aber ein paar Fragen hätte ich dazu, weil mir das aus der Installationsanleitung nicht klar wird.
Leider scheinen auch die zwei Videos von Schatten PV und Meine Energiewende veraltet zu sein, da sich die Config.ini verändert hat.

`#For ESP8266 reduce polling intervall to reduce load
ESP8266PollingIntervall=10000`
Ich nutze einen ESP32. Muss ich hier ein anderes Intervall einstellen, wenn ja, gibt es Erfahrungswerte wie klein dieses werden kann?

`#IP of Device to query
Host=192.168.1781.147`
Ich gehe davon aus, dass hier die IP Adresse meiner open DTU gemeint ist und nicht mein Cerbo GS?

`# Username/Password leave empty if no authentication is required
Username =
Password =`
Ich gehe davon aus, dass hier der Login vom openDTU gemeint ist bzw. wenn der Schieberegler "Nur-Lese-Zugriff auf die Weboberfläche ohne Passwort zulassen " auf TRUE ist, dass ich diese zwei Felder leer lassen kann?

`# 1st inverter
[INVERTER0]
Phase=L1
DeviceInstance=34
AcPosition=0
Servicename=com.victronenergy.pvinverter

 2nd inverter
[INVERTER1]
Phase=L2
DeviceInstance=35
AcPosition=0
Servicename=com.victronenergy.pvinverter`
Die DeviceInstances habe ich kontrolliert. Diese gibt es noch nicht. 
Muss ich die restlichen Inverter 2 bis 10 löschen oder können diese mit defaultwerten bestehen bleiben?

`[TEMPLATE0]
Tasmota Example

Username/Password leave empty if no authentication is required

[TEMPLATE1]
Shelly Gen 1 authenticated and unathenticated example
Documentation: https://shelly-api-docs.shelly.cloud/gen1/#shelly1-1pm-status
`
Ich nutze weder Tasmota noch Shelly. Muss ich hier irgendwas löschen oder kann ich das defaultmäßig stehen lassen? 

Wie sieht mein Problem aus?
Wenn ich `svstat /service/dbus-opendtu` ausführe, dann kommen Werte von 0 bis 4 Sekunden raus. Somit läuft wohl das Skript nicht.

Wenn ich die Website http://192.168.178.147/api/livedata/status öffne, stehen hier alle sinnvollen Werte drin. Das passt also schonmal. 
`{"inverters":[{"serial":"116484258156","name":"Links Platten 1 bis 4","order":0,"data_age":12473,"poll_enabled":true,"reachable":false,"producing":false,"limit_relative":100,"limit_absolute":2000,"AC":{"0":{"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":228.6000061,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"Power DC":{"v":0,"u":"W","d":1},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":235.4760132,"u":"kWh","d":3},"Frequency":{"v":49.99000168,"u":"Hz","d":2},"PowerFactor":{"v":0,"u":"","d":3},"ReactivePower":{"v":0,"u":"var","d":1},"Efficiency":{"v":0,"u":"%","d":3}}},"DC":{"0":{"name":{"u":"Links 1"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":9.199999809,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":61.37400055,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}},"1":{"name":{"u":"Links 2"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":9.199999809,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":59.89099884,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}},"2":{"name":{"u":"Links 3"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":9.199999809,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":58.75500107,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}},"3":{"name":{"u":"Links 4"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":9.199999809,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":55.45600128,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}}},"INV":{"0":{"Temperature":{"v":5.400000095,"u":"°C","d":1}}},"events":1},{"serial":"116484258399","name":"Rechts Platten 5 bis 7","order":1,"data_age":12677,"poll_enabled":true,"reachable":false,"producing":false,"limit_relative":100,"limit_absolute":2000,"AC":{"0":{"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":229.3000031,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"Power DC":{"v":0,"u":"W","d":1},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":121.4369965,"u":"kWh","d":3},"Frequency":{"v":49.97999954,"u":"Hz","d":2},"PowerFactor":{"v":0,"u":"","d":3},"ReactivePower":{"v":0,"u":"var","d":1},"Efficiency":{"v":0,"u":"%","d":3}}},"DC":{"0":{"name":{"u":"Rechts 5"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":10.10000038,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":47.73400116,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}},"1":{"name":{"u":"Rechts 6"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":10.19999981,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":35.86299896,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}},"2":{"name":{"u":"Rechts 7"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":10.10000038,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":28.79400063,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}},"3":{"name":{"u":"Reserve"},"Power":{"v":0,"u":"W","d":1},"Voltage":{"v":0.300000012,"u":"V","d":1},"Current":{"v":0,"u":"A","d":2},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":9.045999527,"u":"kWh","d":3},"Irradiation":{"v":0,"u":"%","d":3,"max":430}}},"INV":{"0":{"Temperature":{"v":5.400000095,"u":"°C","d":1}}},"events":1}],"total":{"Power":{"v":0,"u":"W","d":1},"YieldDay":{"v":0,"u":"Wh","d":0},"YieldTotal":{"v":356.9130249,"u":"kWh","d":3}},"hints":{"time_sync":false,"radio_problem":false,"default_password":false}}`

lasse ich `dbus-spy` laufen, dann bekomme ich als pvinverter nur meinen Fronius angezeigt, aber nicht die zwei Hoymiles HM 1800.

Mein Venus OS ist V3.13 mit large OS.
Open DTU ist v23.12.17
SDK Version v4.4.4

Ich hoffe ihr könnt mir helfen.

Grüße
Jch

Edit: Im VRM oder der Remote Console sehe ich keine neuen Hoymiles Wechselrichter, sondern nur den bekannten Fronius.
Im Cerbo bin ich superuser

Edit2: Ich habe festgestellt, dass ich in der config.ini die IP Adresse von der openDTU falsch geschrieben hatte. Jetzt läuft es soweit, dass ich im VRM in der Device List die zwei Hoymiles finde. Aber in der Remote Console finde ich keine weiteren Geräte. Kommen diese erst, wenn die Sonne scheint?
<img width="389" alt="2023-12-19 21_27_53-Remote Console on LAN – Mozilla Firefox" src="https://github.com/henne49/dbus-opendtu/assets/60581489/e93e100a-a2fe-4ea5-8583-7e4f530662b1">
<img width="611" alt="2023-12-19 21_29_13-BlauerKeller - VRM Portal – Mozilla Firefox" src="https://github.com/henne49/dbus-opendtu/assets/60581489/e61ac951-d7cd-4c93-8e7e-309c57e230fb">

**Comment by henne49** [comment]
Mega Issue, das sollte Referenz werden an Beschreibung. Danke dafür.

warte mal bis die Sonne scheint und sie produzieren. 
du hast AcPosition=0, also verstecken sie sich auch im Fronius, gleiches Problem wie hier: https://github.com/henne49/dbus-opendtu/issues/129

Position shown in Remote Console (0=AC input 1; 1=AC output; 2=AC input 2 please do not use)
