### ISSUE TITLE
Not visible in SetupHelper

### ISSUE THREAD

**Issue by dersch81** [henne49/dbus-opendtu#132]
Hi,

i have the latest SetupHelper and upgraded the latest dbus-opendtu manually. Also added manually dbus-opendtu to setup helper.

But it remains like this:
![image](https://github.com/henne49/dbus-opendtu/assets/13754891/6dff673d-e625-446f-810a-3773642de977)

did i miss something?

**Comment by dsteinkopf** [comment]
SetupHelper support is not yet release. see #122
