### ISSUE TITLE
/Ac/Energy/Forward

### ISSUE THREAD

**Issue by ckvsoft** [henne49/dbus-opendtu#133]
Hallo

is there a reason why in self._dbusservice["/Ac/Energy/Forward"] = pvyield
the entire forward is entered?

Fronius, for example, writes the daily yield that I actually need here

**Comment by henne49** [comment]
You can use daily and total yield. In the config.ini you can select what to use.

**Comment by henne49** [comment]
useYieldDay Is the variable

**Comment by ckvsoft** [comment]
Thanx

lg Chris

**Comment by henne49** [comment]
does this help?
