### ISSUE TITLE
Nichts auf dem Dashboard zu sehen.

### ISSUE THREAD

**Issue by tmonxx** [henne49/dbus-opendtu#134]
Keine Anzeige auf dem Dashboard.

Venus Large v3.13
Cerbo GX und Raspi4
open DTU v24.1.21
Victrom Multiplus 2 und 2x MPPT. Keine AC Inverter.

Zuerst habe ich ein Testsystem mit einem Raspi4 und Venus OS Large v3.13 installiert.
Dann die Open DTU aufgespielt, konfiguriert und gestartet.
Ich sehe meine beidem Hoymilies 800 nur in der Geräteliste und nicht auf dem Dashboard auf dem Cerbo und auch nicht im VRM.
Habe das gleiche auf dem Cerbo, also in einem Live System auch gemacht. Dort auch keine PV Inverter auf dem Dashboard.

Habe auf dem Cerbo v2.93 zuvor ein ältere Version von der Open DTU mit der alten Partitionstabelle laufen gehabt. Da wurde alles auf dem Dashboard als PV-Inverter angezeigt. 

Eine Idee?

<img width="368" alt="image2" src="https://github.com/henne49/dbus-opendtu/assets/121676537/5805c1c3-9cd9-4ad6-a343-598fc010dd99">
<img width="378" alt="image" src="https://github.com/henne49/dbus-opendtu/assets/121676537/d90424a4-0e8c-407a-9550-79b2f7dd904a">

Edit:
Mein AC-in ist inaktiv, weil eine Insel.
Habe die beiden WR jetzt in der config.ini auf AC-out geändert und sie tauchen jetzt auf dem Dashboard auf.
Vor dem Update wurde sie aber auch auf dem inaktiven AC-In angezeigt.
Ich habe die alte Open DTU vor einigen Monaten auch an einem zuvor aktiven AC-in installiert. Die Anlage wurde nur später vom Netz genommen.
Sie sind vermutlich einfach dort "stehen geblieben" obwohl AC-in deaktiviert wurde.
<img width="380" alt="image3" src="https://github.com/henne49/dbus-opendtu/assets/121676537/083cf34f-53dd-4f0d-8410-712b41c3c56b">

Kann also als erledigt betrachtet werden, oder? Die Erkenntnis daraus ist, dass die dementsprechende Ein oder Ausgänge bei der Installation aktiv sein müssen, damit die Sachen auf dem Dashboard angezeigt werden.

**Comment by henne49** [comment]
<img width="773" alt="grafik" src="https://github.com/henne49/dbus-opendtu/assets/4662326/923eb70c-01ce-4711-ba05-9cb958f679ed">

Ja das kann sein, ohne Insel, sind sie wie hier zu sehen auch in 3.13 korrekt angezeigt. Dann bitte auf AC OUT
