### ISSUE TITLE
No function after reinstallation

### ISSUE THREAD

**Issue by e-i-k-e** [henne49/dbus-opendtu#135]
I once completely removed obendtu and downloaded and reinstalled it. 
Now I can't find any functionality.

Running VenusOS 3.14 on a Raspberry 3b.

![image](https://github.com/henne49/dbus-opendtu/assets/83473829/9ad90b94-7aab-45a9-a704-6901cd3d9f89)
[current.zip](https://github.com/henne49/dbus-opendtu/files/14044904/current.zip)

**Comment by henne49** [comment]
you set number of templates to 1, but only configure the second template, therefore it is not working, put your template configuration under [TEMPLATE0], then it should work

**Comment by e-i-k-e** [comment]
Danke!
Ja, dass war bereits der Fehler - wenn man mal schnell was ändert. ;) 
[config.zip](https://github.com/henne49/dbus-opendtu/files/14069404/config.zip)


Ich habe aber ein größeres Problem, und ich vermute das es durch diesen Treiber bzw. eher durch eine falsche Konfiguration verursacht wird.

Ich habe sehr sehr hohe seit einigen Wochen sehr Hohe Verbrauchs sowie Solardaten, die nicht stimmen und anscheinen so ausufern, sobald ich den Treiber aktiv habe. 

Ich füge einige Bilder an, die zeigen, was ich meine.  
![Screenshot 2024-01-26 142459](https://github.com/henne49/dbus-opendtu/assets/83473829/eb3d4dd1-8e1a-46fc-9ce0-1b8eaed78a92)
![Screenshot 2024-01-26 142522](https://github.com/henne49/dbus-opendtu/assets/83473829/30c6bbf6-01bd-49d7-90dd-44f589d89ff0)
![Screenshot 2024-01-26 142606](https://github.com/henne49/dbus-opendtu/assets/83473829/ec5392f4-d695-4c7d-b2cc-edfa6f180f02)
![Screenshot 2024-01-26 220609](https://github.com/henne49/dbus-opendtu/assets/83473829/1ef91f26-7b42-4b34-ac2d-d10900521037)

Im vergleich zu vorgestern, bei nicht aktivem Treiber.
![Screenshot 2024-01-26 221214_vorher](https://github.com/henne49/dbus-opendtu/assets/83473829/141ee408-9505-4332-acfd-38589a56b2d2)

**Comment by henne49** [comment]
Ist das Problem jeden Tag so oder nur seitdem es nun wieder läuft. Weil der Treiber ja einmal lief hat das System die alten Werte und jetzt kamen prlotzlich wieder Solar Daten (Größenordnung von 117kwh) hinzu und das sollte ein einmal off sein?
Stimmen den die Live Verbrauchsdaten?

**Comment by henne49** [comment]
Und schau mal bitte im Template gibt es Faktoren, die du nutzen musst, gibt dein Template den Wert evtl in Wh und Victron nimmt KwH

Außerdem hast du beim Tasmota Servicename=com.victronenergy.inverter obwohl ein Wechselrichter ist, sollte also Servicename=com.victronenergy.pvinverter sein

**Comment by e-i-k-e** [comment]
Ich glaube, ich habe es

Das Template für den Shelly2, anscheinend wird hier Wh übermittelt.

![Screenshot 2024-01-27 095353](https://github.com/henne49/dbus-opendtu/assets/83473829/4e6c9a0a-16bd-4494-948c-b06139c0d76a)

![image](https://github.com/henne49/dbus-opendtu/assets/83473829/e6c2561c-c16d-4618-b527-546224eaaf65)

![image](https://github.com/henne49/dbus-opendtu/assets/83473829/c97837bf-0972-47f7-894f-9f58b26fb99d)

Das mit dem "Tasmota Servicename=com.victronenergy.inverter " sollte korrekt sein, da der Wechselrichter an der Batterie hängt, quasi so wie der MP2.

**Comment by henne49** [comment]
ja den CUST_TOTAL_MULT musst du anpassen auf 0.001, dann sollte es kwh sein

bezüglich VRM kann ich dir nicht sagen, da müsstest du da mal nachfragen

**Comment by e-i-k-e** [comment]
Vielleicht könnt ihr das in der config direkt für das Template des Shelly2 ändern.

**Comment by henne49** [comment]
eigentlich ist das Template in KWH lauffähig, so wurde es von mir in einem Shelly PM gen 2 auch getestet. welchen Shelly 2 meinst du denn?
