### ISSUE TITLE
Feature Request: modify AcPosition via GUI

### ISSUE THREAD

**Issue by konus1** [henne49/dbus-opendtu#136]
Hello, in my [setup](https://www.akkudoktor.net/forum/postid/125554/), I use a bypass switch to be able to switch of the MultiPlus in Winter or during maintenance. 

This leads to my PVinverter to be located in a different place:
in summer mode: Inverter is behind the mulitplus (AcPosition=1)
in winter mode: Inverter is outside the multiplus (AcPosition=0) 

Since the bypass switch is connecting all three phases to one, It also could lead the PVinverter to be conncted on a different phase,

I am looking now for a way change the AcPosition value and the phase of the inverter via GUI.

**Comment by henne49** [comment]
Hi, 

this is nothing we can do, as we have no control of the UI, we just inject data into dbus.
