### ISSUE TITLE
2 opendtu ins VRM integrieren  (HM600 + HMS 2000)

### ISSUE THREAD

**Issue by s3sen** [henne49/dbus-opendtu#141]
Hallo, erstmal vielen Dank für die ganze Mühe, Zeit und die tolle Arbeit.

Aktuell läuft bei mir eine DTU für einen HM600
IP der DTU 192.xxx.xxx.198

nun habe ich wegen dem anderen Funkmodul des HMS 2000 eine weitere DTU mit der IP 192.xxx.xxx.199 aufgesetzt 

beide DTUs sind über ihre  jeweiligen IP Adressen abrufbar und liefern die Daten.

Nun zur Frage: wie bekomme ich die 2te DTU auch ins VRM Portal.

Geht das über ein weiteres Templet ?
Falls ja wie müsste das Templet für 2 DTU Instanzen aussehen? / definiert werden ?

Vorab vielen Dank und Gruß

**Comment by 0x7878** [comment]
Aktuell eher Copy and paste. Du hast dann zwei Instanzen laufen mit der jeweiligen config. Nenne den zweiten Ordner einfach dbus-dtu2 und starte es.

**Comment by s3sen** [comment]
Ok ich versuche es mal, kannst du sagen an welcher Stelle der Befehl geändert werden soll?

**Comment by henne49** [comment]
du musst nur den ordner umbenennen, welchen Befehl meinst du?

**Comment by s3sen** [comment]
Ich hab versucht es zusätzlichin einen Ordner Data2 zu entpacken:

unzip main.zip "dbus-opendtu-main/*" -d /data2

Das hat nicht geklappt, ich bin echt kein Experte in der Sache. 😉

**Comment by henne49** [comment]
nenne den existierenden Ordner um mv alter_name_Ordner neuer_name_Ordner

**Comment by s3sen** [comment]
Danke dir, es funktioniert jetzt.
Ich bin begeistert wie schnell man hier Hilfe bekommt. 

Letzte Frage: 
Kann ich im VRM Dashboard die PV Wechselrichter einzeln anzeigen ? 

In der Geräteliste sind beide drin.

Im Dashboard wird nur die Summe angezeigt und auch keine Phase 

![image](https://github.com/henne49/dbus-opendtu/assets/159629568/10b5ecb9-35db-4d98-a282-066b57dbffad)

![image](https://github.com/henne49/dbus-opendtu/assets/159629568/fa6538a0-a49f-4eff-9d2f-cf8c2cf3d5fe)

**Comment by henne49** [comment]
Schnell geht es auch nicht immer ;-) im Dashboard sieht man nur die Summary. Da können wir nichts machen.

**Comment by s3sen** [comment]
ok, dann ist das so. Das Projekt ist eine extrem coole Sache. Das ermöglicht mir ganz andere Möglichkeiten. Danke 

Ich meine bei einigen im Dashboard die Phasen L1 bis L3 gesehen zu haben. Oder vertue ich mich da gerade ?

**Comment by FrodoVDR** [comment]
@s3sen Wenn deine Hoymiles auf verschiedenen Phasen angeschlossen sind und das entsprechend in der OpenDTU konfiguriert wurde, bekommst du diese als L1-L3 angezeigt.
![grafik](https://github.com/henne49/dbus-opendtu/assets/9979929/7f4af2f0-10e5-4f75-9614-173585e60837)

**Comment by henne49** [comment]
Aber nur auf AC IN, wenn es auf AC OUT ist, dass ist es immer auf der Phase des AC OUT

**Comment by FrodoVDR** [comment]
Auch bei einem 3 phaseigem System?

**Comment by s3sen** [comment]
Danke euch. Find es Mega

**Comment by henne49** [comment]
> Auch bei einem 3 phaseigem System? Das ist Schade.

bei einem 3 Phasigen System, kann ich nicht sagen, da ich keines habe. aber beim Einphasigen steht die Phase fest.

**Comment by s3sen** [comment]
Hi, ich hab das heute testen können. Auch an AC Out zeigt er die unterschiedlichen Phasen im Dashboard ![image](https://github.com/henne49/dbus-opendtu/assets/159629568/f2e81a2e-93e9-4d28-aab6-b747996d14dd)

**Comment by henne49** [comment]
Du hast ein 3 oder 1 phasen system?

**Comment by s3sen** [comment]
L1 hängt ein HM600 und L2 ein HMS2000, im laufe der Woche kommt auf L3 ein weiterer HM2000. Aktuell ist L3 nicht belegt.
Also alles 1 Phasen WR

**Comment by henne49** [comment]
Ist dein Victron System ein 3 Phasen System, nach der Aussage ja, daher kannst du auf AC OUT auch die Phasen sehen? Ansonsten ist die Phase auf AC Out die Phase, auf der der Victron ist.

**Comment by henne49** [comment]
Das war ich :-) Unterscheidung Phase geht nur bei einem 3 Phasen Victron an AC OUT und auf allen Phasen auf AC IN egal ob 1 oder 3 Phasen Victron System. Deswegen sehe ich bei meinen 1 Phasen System nicht die Phase auf AC IN, weil die ja festgelegt ist.

**Comment by s3sen** [comment]
Achso,verstehe, jedenfalls vielen Dank
