### ISSUE TITLE
[Feature Request] Show OpenDTU as separate PV Charger in the VRM

### ISSUE THREAD

**Issue by andreas-bulling** [henne49/dbus-opendtu#144]
OpenDTU is currently not shown as a separate PV Charger in the Victron VRM - like multiple MPPTs are. It would be nice if OpenDTU was also shown separately to more easily see its yield.

**Comment by henne49** [comment]
We write dbus settings and have no influence what is shown on vrm.

**Comment by andreas-bulling** [comment]
That's a pity.

**Comment by andreas-bulling** [comment]
I thought there might be a way given that in the remote console it's shown as a PV charger
