### ISSUE TITLE
Wrong Data - maybe an issue with Shelly 3EM Code

### ISSUE THREAD

**Issue by fellpower** [henne49/dbus-opendtu#150]
Hey 

i have a balcony pv with 2 x 410W modules and a Hoymiles HM-800 as PV Inverter. works great, opendtu works like a charm.

- I have no multigrid II
- Hoymiles HM800 at L3 conncted
- Raspi4 as CerboGX with Venus OS
- Shelly 3 EM installed in the Mainline, in FRONT af the whole house - and installed the code in VenusOS for it

Now in my oppinion something is mathematical wrong. See the picture

i get 40W from my Hoymiles Inverter - that shows as -40W, thats correct, because the shelly is measuring negative, if im bring in power, that i dont use.

<img width="521" alt="venus" src="https://github.com/henne49/dbus-opendtu/assets/73786796/9f4c73ec-6e3f-40fb-9857-ed2a0e626e19">

i confd the opendtu code as pvinverter. because its doing this. it on L3 and inverting fine.

[INVERTER0]
Phase=L3
DeviceInstance=34
AcPosition=1
Servicename=com.victronenergy.pvinverter

Shelly is confed like that: 

[DEFAULT]
AccessType = OnPremise
SignOfLifeLog = 1
CustomName = Shelly 3EM
DeviceInstance = 40
Role = grid
Position = 0
LogLevel=ERROR

[ONPREMISE]
Host=192.168.0.69
Username=
Password=
L1Position = 1

if im put opendtu in at ac pos 0 - it wont show up (plz why?), if i put it as ac out 1 - it works, but for the cerbo its a load, so it puts that -40W to +40W at the load end. 

the shelly is confed on grid40

So something is wrong here - maybe with the shelly code, or yours, i dont know. or im wrong :P

**Comment by henne49** [comment]
it works fine and well with a real existing multiplus, also rather check the values you see under the individual devices in Venus Console. 

All Display on Venus Console or VRM Console is out of our control, as we write only to dbus according to documentation. Victron is in charge and control for the rest.
