### ISSUE TITLE
Falsche Installationsanleitung

### ISSUE THREAD

**Issue by KarlMeier1933** [henne49/dbus-opendtu#153]
Die Installationsdateien werden nach „/data/dbus-opendtu-main“ kopiert.

Bei den weiteren Installationsschritten wird auf ein Verzeichnis ohne „main“ verwiesen. Also „/data/dbus-opendtu“.

Früher hat das funktioniert, aber nach der letzten Änderung hat sich wohl das Installationsverzeichnis geändert. Wenn man das übersieht kommt man nach dem Herunterladen der Dateien nicht weiter.

**Comment by henne49** [comment]
Das war schon immer so

wget -O main.zip https://github.com/henne49/dbus-opendtu/archive/refs/heads/main.zip
unzip main.zip "dbus-opendtu-main/*" -d /data
mv /data/dbus-opendtu-main /data/dbus-opendtu
chmod a+x /data/dbus-opendtu/install.sh

daher gibt es den 3.Schritt

**Comment by KarlMeier1933** [comment]
Komisch, dann wurde aus irgendwas Grund der Move-Befehl nicht ausgeführt. Ich musste das Ganze deinstallieren und neu installieren und dabei gab es dieses Problem.
