### ISSUE TITLE
Comment in config.ini is wrong

### ISSUE THREAD

**Issue by Sonny13** [henne49/dbus-opendtu#155]
Hi, thanks for this amazing project.

The documentation states:
AcPosition - > Position shown in Remote Console (0=AC input 1; 1=AC output; 2=AC **input** 2)

But the comment in the config.ini file states:
AcPosition 0=AC input 1; 1=AC output; 2=AC **output** 2

I checked with my setup and NodeRed. AC input 2 seams to be correct.

**Comment by henne49** [comment]
Would you have a photo, where this is loactwd at the multiplus? I ever only used 0 and 1, but never 2

**Comment by Sonny13** [comment]
Position Information in Node Red of HMS2000 
![Screenshot 2024-03-22 163955](https://github.com/henne49/dbus-opendtu/assets/7512993/b3705289-4d00-40ac-8823-2b669f805ced)

In remote console or vrm the HMS2000 (connected on config 2, and AC out 2) shows up on the grid side of the multiplus, which is wrong.
The HM800 (connected on config 1, and AC out 1) shows up un the correct side.
![Screenshot 2024-03-22 163922](https://github.com/henne49/dbus-opendtu/assets/7512993/3dd051fc-d023-444d-8fe1-3e60f20aba5e)

**Comment by henne49** [comment]
OK thank you for this, we will check this

can you let me know, what node-red package your are using here?

**Comment by henne49** [comment]
fixed in https://github.com/henne49/dbus-opendtu/tree/henne49-patch-4
