### ISSUE TITLE
Nach Update von openDTU V23-12-18 auf V24-04-05 geht die Einbindung bei Victron nich mehr

### ISSUE THREAD

**Issue by Jch24** [henne49/dbus-opendtu#156]
Hallo,

ich hatte Monatelang die Version vom 18.12.2023 von der OpenDTU auf dem ESP32 installiert.
Gestern habe ich das Update auf die neueste Version vom 05.04.2024 gemacht. Nun wird mein Balkonkraftwerk nichtmehr im Victron VRM erkannt. 

Die Fehlermeldung laut current.log ist:
"You do not have the latest OpenDTU Version to run this script"

Daraufhin habe ich ein Downgrade wieder auf die Version vom 18.12.2023 gemacht. Nun geht leider gar nichts mehr, da mein ESP32 nun gar nichts mehr macht. Er bootet nicht einmal mehr.

Kann mir jemand helfen, den ESP32 wieder zum leben zu erwecken?

@henne49 Vielleicht schaust Du dir auch mal den Fehler mit der "neuesten Version" an"

Grüße
Jch

**Comment by Jch24** [comment]
nachdem ich per USB die Factory-FW aufspielen musste läuft nun zumindest wieder das Victron Plugin für die Dezember-Version

**Comment by 21-Jailbraik-21** [comment]
Guten Abend, du musst auf dem Victon System das Plug in einmal deinstallieren und neu installieren in der aktuellsten Version. Dann kann man auch die aktuelle Open DU benutzen.
