### ISSUE TITLE
Confusion on AC Load calculation fpr "BatteryInverter"

### ISSUE THREAD

**Issue by sequarell** [henne49/dbus-opendtu#162]
Not quite sure if this is even a bug of dbus-opendtu or located somewhere else, but I think it is worth reporting here.
i have configured bdus-opendtu as battery inverter, and I see an issue with the vicron AC-Load calculation when the inverter output is bigger than the current load  of the single line:

![image](https://github.com/henne49/dbus-opendtu/assets/11975775/90783750-0155-4beb-a2bb-29a89429fb5a)

AC Load: The "real" total load here is about ~2.2kw .. L1 (inverter is connected here) shoud have round about 450w ,L2 & L3 are correct.
AC Input is correct. The invertter on L1 exports, L3 imports.. The sum is about 1kw, another 1.2kw coming from the inverter... 200w going to battery

At first glance, it seems that the AC calculation does simply add the inverter power to L1, not recognizing the negative load on L1. 

1. Which Venus OS are you using? -> 3.13
2. Which Victron Device?-> Cerbo GX
3. Which DTU? -> openDTU
4. Which Template Device? -> none, BatteryInverter

**Comment by Arkadier** [comment]
The same here.

I have my HM800 on AC-Out. The power is balanced by frequency shiffting. I works well. Before update i saw my HM800 as a PV Inverter. My AC loads too.
Now I see only the balanced loads on my AC-Out. The value is correct.

Which Venus OS are you using? -> latest 3.31
Which Victron Device?-> Cerbo GX
Which DTU? -> openDTU firmware latest 24.4.12

![image](https://github.com/henne49/dbus-opendtu/assets/166981945/73f42abd-829e-4ef8-bf88-26fa2714353a)
![image](https://github.com/henne49/dbus-opendtu/assets/166981945/3fecf36f-4b60-4757-aeb9-99ede9c8729a)

**Comment by henne49** [comment]
please check what you see on Venus/Cerbo Device, as this is where we write data to dbus. 

Also what Victron Device do you use? a Mutliplus II?

Also which config inverter is on which phase?

the calculation is done by Venus, so if you write data to the wrong AC line or wrong phase through our configuration, the view is also wrong.

**Comment by henne49** [comment]
Good 👍🏻
