### ISSUE TITLE
Support Opendtu onbattery

### ISSUE THREAD

**Issue by OnkelQuincy** [henne49/dbus-opendtu#166]
**Follow the Troubleshooting Section**
Change the Logging Parameter under DEFAULT in /data/dbus-opendtu/config.ini to Logging = DEBUG, please revert, once debugging and troubleshooting is complete. Rerun the script and share the current.log and config.ini file.
[Troubleshooting Section](https://github.com/henne49/dbus-opendtu#troubleshooting )

**Describe the Problem**
I use a opendtu onbattery. Two inverters are added. I can´t get connection to Multiplus II 3000 GX with this dbus-opendtu.
Values and opendtu is not shown ind VRM and RemoteConsole.

**Device you are using**
1. V3.31
2. Multiplus II 3000 GX
3. OpenDTu onbattery
4. Which Template Device?
SDK v4.4.6-dirty

**Expected behavior**
PV value shown on opendtu onbattery display should be shown in Victron console and VRM

**Screenshots**

![grafik](https://github.com/henne49/dbus-opendtu/assets/168893107/fd091e97-1953-4942-a462-40cb0d8b12b4)
![grafik](https://github.com/henne49/dbus-opendtu/assets/168893107/8406ef22-7643-4cf0-9a09-4ecc62b0039f)
![grafik](https://github.com/henne49/dbus-opendtu/assets/168893107/2fb3a137-e52c-4fdb-8f20-663ee89b128f)

**Additional context**

**Comment by henne49** [comment]
Please follow the guide: 

Follow the Troubleshooting Section
Change the Logging Parameter under DEFAULT in /data/dbus-opendtu/config.ini to Logging = DEBUG, please revert, once debugging and troubleshooting is complete. Rerun the script and share the current.log and config.ini file.
[Troubleshooting Section](https://github.com/henne49/dbus-opendtu#troubleshooting)

**Comment by OnkelQuincy** [comment]
[config.txt](https://github.com/henne49/dbus-opendtu/files/15209866/config.txt)

Where can I find the current.log ?

**Comment by henne49** [comment]
Same folder as the config.ini

**Comment by OnkelQuincy** [comment]
![grafik](https://github.com/henne49/dbus-opendtu/assets/168893107/809b8278-500d-4bb8-be60-9a9be3509908)

Hi, sorry not found. In this folder is no current.log  Could you still take a look at the other information I provided ?

**Comment by henne49** [comment]
Have ever done this step? https://github.com/henne49/dbus-opendtu?tab=readme-ov-file#how-to-install

It seems the service is not running at all.

**Comment by OnkelQuincy** [comment]
I made it ! Removed everything and startet again. It´s working ! Great job - thanks !!!

![grafik](https://github.com/henne49/dbus-opendtu/assets/168893107/a7102f1a-bd60-4e4f-9b5c-363bf67fb0d7)

**Comment by OnkelQuincy** [comment]
👍
