### ISSUE TITLE
README.md  Fehler eingeschlichen ?

### ISSUE THREAD

**Issue by buntelichter** [henne49/dbus-opendtu#178]
Hallo zusammen,
in der letzten Woche hat sich ja einiges geändert 👍, vielen Dank dafür.
Hat sich da ein Fehler eingeschlichen? 
![Screenshot 2](https://github.com/henne49/dbus-opendtu/assets/130780992/f462c905-2174-4595-99e7-6bcea87dee36)
und sollte das jetzt nicht  "config.example" heißen ?
![Screenshot 1](https://github.com/henne49/dbus-opendtu/assets/130780992/926a8b6c-a153-4cfd-8664-b00e167d3250)
Liebe Grüße.

**Comment by henne49** [comment]
Ja vielen Dank!
