### ISSUE TITLE
zero Values ​​different openDTU/Template

### ISSUE THREAD

**Issue by e-i-k-e** [henne49/dbus-opendtu#35]
Just a little thing. :)

The zero values ​​are displayed differently in Venus.
Template (Tasmota/Shelly) 0.0W
openDTU: 0W

![image](https://user-images.githubusercontent.com/83473829/220197314-b15c8d3c-28f5-445d-bbb3-e9ab7aeee4c1.png)
Don't let the name _opendtu unsettle you. This is a Tasmota device

**Comment by henne49** [comment]
at night it should be ---

We take the numbers as we get them from the devices and do no manipulation, this is easier and less error prone. It is only cosmetic. Also OpenDTU shows 1 number after the dot as well if larger than 0. 

So this should all be good.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/4662326/220199628-e8f4a3ad-c2c6-490d-a088-769488c9ecec.png">

**Comment by e-i-k-e** [comment]
Thanks for the info.
