### ISSUE TITLE
Error after updateing Cerbo to 2.93

### ISSUE THREAD

**Issue by bear30** [henne49/dbus-opendtu#36]
Hello,

after updating the cerbo from 2.92 to 2.93 my HM-1500 disapears in the victron remote console. By the way this victron update change my ssh password to ???. I think this is a victron mistake. Ok, i restore the original ssh password. Nothing happens. Then i reinstall dbus-opendtu to the newest version, but nothing changes. In dbus spy i can see the dbus-device for 1 sec, the it disapears for 5 sec, ... and so again and again. Then i look into the log file and see this error messages from screenshot. Did you have any idea to this problem?

![Screenshot_20230221_085135](https://user-images.githubusercontent.com/5871470/220283832-2b2eaa65-628b-4477-8b85-63f7fea357dd.png)

Thank you for your work!!!

**Comment by bear30** [comment]
![Screenshot_20230221_090851](https://user-images.githubusercontent.com/5871470/220285359-4185c1ee-3bed-463f-9ce7-4abf46361fa0.png)

**Comment by henne49** [comment]
Hi, this seems to be a very old config and the deviceinstance should be rather something like 34.

Also your code seems very old, please upgrade to the new release code from yesterday. Repeat the installation steps.

and yes with every update the ssh password is overwritten, why you should use ssh key authentication: https://www.victronenergy.com/live/ccgx:root_access#installing_ssh_keys

**Comment by bear30** [comment]
Hello, thank you for your fast response. 

By the way my installation was 5 weeks old... 

Now i delete first the directory from cerbo and reinstall and configure dbus-optendtu. Now it works. 

Thank you!

**Comment by henne49** [comment]
Glad to hear, well the project is only 10 weeks old, so in that it is old, we did some huge in the meanwhile.
