### ISSUE TITLE
Converting response from 192.168.0.104 to JSON failed:

### ISSUE THREAD

**Issue by Pycek2** [henne49/dbus-opendtu#55]
Hi
After installation opendtu want start properly.
current.log in attachment
 
[current.log](https://github.com/henne49/dbus-opendtu/files/11061445/current.log)
![hoymiles2023-03-23 140547](https://user-images.githubusercontent.com/7480502/227507970-a272dff7-b5a1-4676-b48a-314ee739a65f.jpg)

**Comment by henne49** [comment]
Well it does not work with the official one, you need to run [ahoy](https://ahoydtu.de/) or [opendtu](https://github.com/tbnobody/OpenDTU).

**Comment by dsteinkopf** [comment]
As we'll not be able to help here more, I'll close this. Feel free to open a new issue, if you still have problems when using ahoy or opendtu.
