### ISSUE TITLE
Service won’t start anymore

### ISSUE THREAD

**Issue by testpaul999** [henne49/dbus-opendtu#86]
**Follow the Troubleshooting Section**
Change the Logging Parameter under DEFAULT in /data/dbus-opendtu/config.ini to Logging = DEBUG, please revert, once debugging and troubleshooting is complete. Rerun the script and share the current.log and config.ini file.
[Troubleshooting Section](https://github.com/henne49/dbus-opendtu#troubleshooting )

**Describe the Problem**
A clear and concise description of what the issue is.
- Service won’t start anymore
- 
**Device you are using**
1. Which Venus OS are you using? - v3.00~37\39
2. Which Victron Device? - RPI 
3. Which DTU? - opendtu - v23.5.3
4. Which Template Device? - no, only pvinverter 0

**Expected behavior**
Service won’t start anymore

**Screenshots**

**Additional context**
[New Text Document.txt](https://github.com/henne49/dbus-opendtu/files/11428131/New.Text.Document.txt)

**Comment by dsteinkopf** [comment]
This seems to be the core problem (from "New Text Document.txt"):
```
root@raspberrypi2:~#  python /data/dbus-opendtu/dbus-opendtu.py
Traceback (most recent call last):
  File "/data/dbus-opendtu/dbus-opendtu.py", line 16, in <module>
    import tests
  File "/data/dbus-opendtu/tests.py", line 13, in <module>
    from dbus_service import DbusService
  File "/data/dbus-opendtu/dbus_service.py", line 7, in <module>
    from vedbus import VeDbusService
ModuleNotFoundError: No module named 'vedbus'
```

@testpaul999: Is Venus version 'v3.00~37\39' a current beta version? Then, this might be the source of the problem (which we'll have to solve). Did it still work when using Venus 2.x?

**Comment by testpaul999** [comment]
Is Venus version 'v3.00~37\39' a current beta version? - yes!
Did it still work when using Venus 2.x? - don’t know, but run fine with Venus-os v3.0.0~32.
I‘ll go back and test, thx for idea.

**Comment by dsteinkopf** [comment]
If it is working on the older versions, then it seems to be some change they made in the new version. We'll have to adapt this in our script then...

**Comment by testpaul999** [comment]
So have test.
Have Setup a 2.94 plain on RPI.
Install with the suggested way from GitHub.
But same issue.
Then I use a backup und now it run with 2.94.
Next I‘ll upgrade to 3.00-39 and this also run
Maybe some wrong with the files at GitHub?

Grüße aus Berlin

**Comment by henne49** [comment]
we need the current.log file again, or can you confirm, that the error is the same?

**Comment by testpaul999** [comment]
👍🏻 thx run fine
