### ISSUE TITLE
Device charger instead of pvinverter possible? :-P

### ISSUE THREAD

**Issue by Hofyyy** [henne49/dbus-opendtu#89]
Hello,

first thanks again for the great project.
Might it be possible to add also the charger?
com.victronenergy.evcharger

Then I would be able to set the right stats via MQTT :-)

Best regards
Sebastian

**Comment by Hofyyy** [comment]
I found already a project which seems more close to my request, so I will close this issue here.
https://github.com/vikt0rm/dbus-goecharger

**Comment by henne49** [comment]
We would have a look to add it, to have all possibilities in one universal driver.

**Comment by Hofyyy** [comment]
maybe this helps, here it is already working
https://github.com/freakent/dbus-mqtt-devices/pull/33/files
